name: CI_demo

no:
  push:

jobs:
  build:
  runs-on: ubuntu-latest

  stepd:
  - name: Check out
  - uses: actions/checkout@v3
  - name: setup python
  - uses: actions/setup-python@v4
    with:
      python-version: 3.11

  - name: CML
  - uses: iterative/setup-cml@v2
  - name: install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    - name: run main
      run: |
        python main.py

    - name: Run Tests
      run: |
        python -m unittest discover

    - name: Create CML report 
      env:
        REPO_TOKEN: ${{ secrets.CI_DEMO_TOKEN}}
      run: |

        echo "# First Line of the reort">> report.md
        echo "## Bar plot">> report.md
        echo '![](./bar.png "Bar plot")'>> report.md
        echo "## Line Plots">> report.md
        echo '![](./lines.png "Bar Plot")'>> report.md

        cml commet create report.md